server:
  port: 9000
  servlet:
    context-path: /app-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres?currentSchema=grm
    username: postgres
    password: postgres
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
  rabbitmq:
    port: 5672

rabbitMq:
  queue-name: grm-queue
  exchange-name: grm-exchange
  binding-key: grm-key
